name: Generate metrics
on:
  schedule: [{cron: "0 * * * *"}] # 매 시간마다 업데이트
  workflow_dispatch: # 수동 실행도 가능

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, ruby, javascript
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8